pipeline {
    agent any

    environment {
        IMAGE_NAME = 'cake-shop'
        CONTAINER_NAME = 'cake-shop-container'
    }

    stages {
        stage('Clone Repo') {
            steps {
                git url: 'https://github.com/Tanvir0922/onlinecakeshop.git', branch: 'master'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Stop and Remove Old Container') {
            steps {
                script {
                    sh "docker stop $CONTAINER_NAME || true"
                    sh "docker rm $CONTAINER_NAME || true"
                }
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8080:80 --name $CONTAINER_NAME $IMAGE_NAME'
            }
        }
    }
}
